"""Shared theme palettes for the QML-based modern UI."""
from __future__ import annotations

from config import settings

THEMES: dict[str, dict[str, dict[str, object]]] = {
    "arcade_mario": {
        "light": {
            "background": ["#00AEEF", "#7EDBFF", "#FFD700"],
            "panel": "#FFF6D6",
            "panelAlt": "#FFE082",
            "primary": "#FF0000",
            "secondary": "#00AEEF",
            "accent": "#00FF00",
            "text": "#2B1608",
            "textSoft": "#8B4513",
            "price": "#C40000",
            "buttonGradient": ["#FF0000", "#FFD700", "#00AEEF"],
            "buttonText": "#FFFFFF",
            "volume": "#B36A20",
            "glassOpacity": 0.78,
            "particleColor": "#FFD700",
        },
        "dark": {
            "background": ["#13284F", "#1E3A6B", "#8B4513"],
            "panel": "#1F1812",
            "panelAlt": "#312212",
            "primary": "#FF4D4D",
            "secondary": "#4DD7FF",
            "accent": "#FFD700",
            "text": "#FFF6D6",
            "textSoft": "#FFD56A",
            "price": "#FFD700",
            "buttonGradient": ["#FF0000", "#00AEEF", "#FFD700"],
            "buttonText": "#FFF6D6",
            "volume": "#FFB44D",
            "glassOpacity": 0.28,
            "particleColor": "#FFD700",
        },
    },
    "blue_ocean": {
        "light": {
            "background": ["#DBEAFE", "#EFF6FF", "#BFDBFE"],
            "panel": "#FFFFFF",
            "panelAlt": "#DFF3FF",
            "primary": "#2563EB",
            "secondary": "#0EA5E9",
            "accent": "#FACC15",
            "text": "#0F172A",
            "textSoft": "#334155",
            "price": "#1D4ED8",
            "buttonGradient": ["#2563EB", "#0EA5E9", "#38BDF8"],
            "buttonText": "#FFFFFF",
            "volume": "#2563EB",
            "glassOpacity": 0.74,
            "particleColor": "#BAE6FD",
        },
        "dark": {
            "background": ["#020617", "#0F172A", "#1D4ED8"],
            "panel": "#10213A",
            "panelAlt": "#17304F",
            "primary": "#60A5FA",
            "secondary": "#22D3EE",
            "accent": "#FACC15",
            "text": "#E2E8F0",
            "textSoft": "#CBD5E1",
            "price": "#93C5FD",
            "buttonGradient": ["#1D4ED8", "#2563EB", "#38BDF8"],
            "buttonText": "#E2E8F0",
            "volume": "#7DD3FC",
            "glassOpacity": 0.28,
            "particleColor": "#38BDF8",
        },
    },
    "yellow_industrial": {
        "light": {
            "background": ["#FFF7ED", "#FEF3C7", "#FDE68A"],
            "panel": "#FFFBEA",
            "panelAlt": "#FFE8B0",
            "primary": "#CA8A04",
            "secondary": "#F59E0B",
            "accent": "#F97316",
            "text": "#1F2937",
            "textSoft": "#57534E",
            "price": "#A16207",
            "buttonGradient": ["#FACC15", "#F59E0B", "#F97316"],
            "buttonText": "#1F2937",
            "volume": "#B45309",
            "glassOpacity": 0.72,
            "particleColor": "#FDE68A",
        },
        "dark": {
            "background": ["#1C1917", "#292524", "#78350F"],
            "panel": "#2A2420",
            "panelAlt": "#382D20",
            "primary": "#FACC15",
            "secondary": "#FB923C",
            "accent": "#F97316",
            "text": "#FAFAF9",
            "textSoft": "#E7E5E4",
            "price": "#FDE68A",
            "buttonGradient": ["#CA8A04", "#EA580C", "#FACC15"],
            "buttonText": "#FFFBEA",
            "volume": "#FDBA74",
            "glassOpacity": 0.3,
            "particleColor": "#FDBA74",
        },
    },
    "green_nature": {
        "light": {
            "background": ["#DCFCE7", "#ECFDF5", "#BEF264"],
            "panel": "#FFFFFF",
            "panelAlt": "#D9F99D",
            "primary": "#16A34A",
            "secondary": "#22C55E",
            "accent": "#84CC16",
            "text": "#14532D",
            "textSoft": "#3F6212",
            "price": "#15803D",
            "buttonGradient": ["#16A34A", "#22C55E", "#84CC16"],
            "buttonText": "#FFFFFF",
            "volume": "#4D7C0F",
            "glassOpacity": 0.7,
            "particleColor": "#86EFAC",
        },
        "dark": {
            "background": ["#052E16", "#14532D", "#166534"],
            "panel": "#14452A",
            "panelAlt": "#1D5B35",
            "primary": "#4ADE80",
            "secondary": "#2DD4BF",
            "accent": "#A3E635",
            "text": "#ECFDF5",
            "textSoft": "#D9F99D",
            "price": "#86EFAC",
            "buttonGradient": ["#166534", "#16A34A", "#84CC16"],
            "buttonText": "#ECFDF5",
            "volume": "#BEF264",
            "glassOpacity": 0.28,
            "particleColor": "#4ADE80",
        },
    },
    "sunset_energy": {
        "light": {
            "background": ["#FFF1F2", "#FFE4E6", "#FED7AA"],
            "panel": "#FFFFFF",
            "panelAlt": "#FFE4EA",
            "primary": "#EC4899",
            "secondary": "#F43F5E",
            "accent": "#FF6B35",
            "text": "#111827",
            "textSoft": "#64748B",
            "price": "#C2185B",
            "buttonGradient": ["#EC4899", "#F43F5E", "#FF6B35"],
            "buttonText": "#FFFFFF",
            "volume": "#D946EF",
            "glassOpacity": 0.72,
            "particleColor": "#FDBA74",
        },
        "dark": {
            "background": ["#1F1020", "#3B1020", "#7C2D12"],
            "panel": "#311221",
            "panelAlt": "#48172B",
            "primary": "#F472B6",
            "secondary": "#FB7185",
            "accent": "#FB923C",
            "text": "#FFF7ED",
            "textSoft": "#FECDD3",
            "price": "#FDB4C0",
            "buttonGradient": ["#DB2777", "#E11D48", "#F97316"],
            "buttonText": "#FFF7ED",
            "volume": "#F9A8D4",
            "glassOpacity": 0.28,
            "particleColor": "#FB7185",
        },
    },
    "purple_modern": {
        "light": {
            "background": ["#F5F3FF", "#EEF2FF", "#DDD6FE"],
            "panel": "#FFFFFF",
            "panelAlt": "#E9D5FF",
            "primary": "#7C3AED",
            "secondary": "#8B5CF6",
            "accent": "#06B6D4",
            "text": "#1E1B4B",
            "textSoft": "#5B21B6",
            "price": "#6D28D9",
            "buttonGradient": ["#7C3AED", "#8B5CF6", "#06B6D4"],
            "buttonText": "#FFFFFF",
            "volume": "#7C3AED",
            "glassOpacity": 0.72,
            "particleColor": "#C4B5FD",
        },
        "dark": {
            "background": ["#0F0722", "#1E1B4B", "#312E81"],
            "panel": "#23185B",
            "panelAlt": "#302574",
            "primary": "#A78BFA",
            "secondary": "#C084FC",
            "accent": "#22D3EE",
            "text": "#F5F3FF",
            "textSoft": "#DDD6FE",
            "price": "#C4B5FD",
            "buttonGradient": ["#6D28D9", "#7C3AED", "#06B6D4"],
            "buttonText": "#F5F3FF",
            "volume": "#DDD6FE",
            "glassOpacity": 0.28,
            "particleColor": "#A78BFA",
        },
    },
}


def palette_for(theme_name: str, mode: str) -> dict[str, object]:
    safe_theme = theme_name if theme_name in THEMES else settings.UI_THEME
    if safe_theme not in THEMES:
        safe_theme = "sunset_energy"
    safe_mode = mode if mode in ("light", "dark") else settings.UI_MODE
    if safe_mode not in ("light", "dark"):
        safe_mode = "light"
    return THEMES[safe_theme][safe_mode]

